package amlich

import (
	"bufio"
	"fmt"
	"os"
	"testing"
)

// The golden files are generated by the production JS implementation inside
// TEdu (see testdata/README). The Go port must reproduce it bit-for-bit,
// except where this library deliberately validates harder (see below).

func TestGoldenLowLevel(t *testing.T) {
	f, err := os.Open("testdata/golden_lowlevel.txt")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	n := 0
	for sc.Scan() {
		var kind string
		var a, tz, want int
		if _, err := fmt.Sscan(sc.Text(), &kind, &a, &tz, &want); err != nil {
			t.Fatalf("bad line %q: %v", sc.Text(), err)
		}
		var got int
		switch kind {
		case "NM":
			got = newMoonDay(a, float64(tz))
		case "SL":
			got = sunLongitude(a, float64(tz))
		default:
			t.Fatalf("unknown kind %q", kind)
		}
		if got != want {
			t.Fatalf("%s(%d, tz=%d) = %d, golden %d", kind, a, tz, got, want)
		}
		n++
	}
	if n < 1000 {
		t.Fatalf("suspiciously few golden rows: %d", n)
	}
}

type goldenRow struct {
	tz, ly, lm, ld, leap int
	sy, sm, sd           int
}

func loadGolden(t *testing.T) []goldenRow {
	t.Helper()
	f, err := os.Open("testdata/golden_lunar2solar.txt")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	var rows []goldenRow
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		var r goldenRow
		if _, err := fmt.Sscan(sc.Text(), &r.tz, &r.ly, &r.lm, &r.ld, &r.leap, &r.sy, &r.sm, &r.sd); err != nil {
			t.Fatalf("bad line %q: %v", sc.Text(), err)
		}
		rows = append(rows, r)
	}
	return rows
}

// classify pre-computes which golden rows are artifacts of the reference JS
// being permissive where this library validates:
//   - leap=1 in a year whose month has no leap: JS silently answers as if
//     leap=0; we return ErrInvalidLunarDate.
//   - day 30 of a 29-day month: JS silently overflows into the next month;
//     we return ErrInvalidLunarDate.
func classify(rows []goldenRow) (regular map[goldenRow]bool, leapArtifacts, overflowCandidates []goldenRow) {
	base := map[string][3]int{}
	for _, r := range rows {
		if r.leap == 0 {
			base[fmt.Sprint(r.tz, r.ly, r.lm, r.ld)] = [3]int{r.sy, r.sm, r.sd}
		}
	}
	regular = make(map[goldenRow]bool, len(rows))
	for _, r := range rows {
		if r.leap == 1 {
			if b, ok := base[fmt.Sprint(r.tz, r.ly, r.lm, r.ld)]; ok && b == [3]int{r.sy, r.sm, r.sd} {
				leapArtifacts = append(leapArtifacts, r)
				continue
			}
		}
		if r.ld == 30 {
			overflowCandidates = append(overflowCandidates, r)
			continue
		}
		regular[r] = true
	}
	return
}

func TestGoldenLunarToSolar(t *testing.T) {
	rows := loadGolden(t)
	regular, leapArtifacts, overflow := classify(rows)

	checked := 0
	for r := range regular {
		y, m, d, err := LunarToSolar(LunarDate{Year: r.ly, Month: r.lm, Day: r.ld, Leap: r.leap == 1}, Zone(r.tz))
		if err != nil {
			t.Fatalf("LunarToSolar(%d/%d/%d leap=%d tz=%d): unexpected error %v", r.ld, r.lm, r.ly, r.leap, r.tz, err)
		}
		if y != r.sy || m != r.sm || d != r.sd {
			t.Fatalf("LunarToSolar(%d/%d/%d leap=%d tz=%d) = %d-%d-%d, golden %d-%d-%d",
				r.ld, r.lm, r.ly, r.leap, r.tz, y, m, d, r.sy, r.sm, r.sd)
		}
		checked++
	}
	if checked < 25000 {
		t.Fatalf("too few regular rows checked: %d", checked)
	}

	for _, r := range leapArtifacts {
		if _, _, _, err := LunarToSolar(LunarDate{Year: r.ly, Month: r.lm, Day: r.ld, Leap: true}, Zone(r.tz)); err == nil {
			t.Fatalf("leap artifact %+v: expected ErrInvalidLunarDate, got success", r)
		}
	}

	for _, r := range overflow {
		y, m, d, err := LunarToSolar(LunarDate{Year: r.ly, Month: r.lm, Day: 30, Leap: r.leap == 1}, Zone(r.tz))
		if err == nil {
			if y != r.sy || m != r.sm || d != r.sd {
				t.Fatalf("day-30 row %+v: got %d-%d-%d", r, y, m, d)
			}
			continue // genuine 30-day month, matches golden
		}
		// We rejected it: prove the golden value was the JS overflow artifact —
		// converting the golden solar date back must land on day 1 of a month.
		l, err2 := SolarToLunar(r.sy, r.sm, r.sd, Zone(r.tz))
		if err2 != nil || l.Day != 1 {
			t.Fatalf("day-30 row %+v rejected, but golden solar is not a month start (lunar %v, err %v)", r, l, err2)
		}
	}
	t.Logf("regular=%d leapArtifacts=%d day30=%d", checked, len(leapArtifacts), len(overflow))
}

func TestGoldenRoundTrip(t *testing.T) {
	rows := loadGolden(t)
	regular, _, _ := classify(rows)
	for r := range regular {
		l, err := SolarToLunar(r.sy, r.sm, r.sd, Zone(r.tz))
		if err != nil {
			t.Fatalf("SolarToLunar(%d-%d-%d tz=%d): %v", r.sy, r.sm, r.sd, r.tz, err)
		}
		want := LunarDate{Year: r.ly, Month: r.lm, Day: r.ld, Leap: r.leap == 1}
		if l != want {
			t.Fatalf("SolarToLunar(%d-%d-%d tz=%d) = %v, want %v", r.sy, r.sm, r.sd, r.tz, l, want)
		}
	}
}

func TestGoldenFilesHaveKoreanZone(t *testing.T) {
	rows := loadGolden(t)
	tz9 := 0
	for _, r := range rows {
		if r.tz == 9 {
			tz9++
		}
	}
	if tz9 == 0 {
		t.Fatal("golden file contains no UTC+9 rows")
	}
}
